### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by gitgabbs** [JanneKarki/Algoritmien-vertailu-sovellus#1]
*Project version from 15th august at 10.47pm* <br/>

As a first thing, sorry if I misunderstood something (especially comments throughout the code) because I just copied and pasted it into google translate.  <br/>
<br/>

**General:**
-	I think it’s cool that there’s a choice of 2 algorithms to solve the maze and user actually can choose which one wants to use
-	Great idea to measure time the execution takes, nicely shows how fast the algorithm is
-	I really like the idea of the ```Explore()``` class. Makes perfect sense to reuse those functions in both Tremaux and Wall Follower, and not just rewrite everything in each of those classes
-	I can’t visualize the maze since there is no src/data/maze.png path (I didn’t find any maze.png in the directory) – but I guess it’s for now and it just hasn’t been done yet, right? <br/>

Since I couldn’t visualize the created and solved maze by just running that code, I tested classes ```Tremaux``` and ```WallFollower``` by printing the output (solved maze) in the terminal – in both classes I added the function ```print_in_terminal()``` <br/>
<br/>

**Tremaux:**

Maze printed in terminal: ```#``` - wall, ```.```  - path <br/>
<img width="647" alt="terminal_print_tremaux" src="https://user-images.githubusercontent.com/97029420/185743969-f5e42af5-b316-4d72-bf1e-4d2dd1b228b2.png">

If the entrance is always in the left upper corner and exit in the right bottom corner, then the maze seems incorrect on the screenshot of the terminal attached above. There’s a wall at (0,0), meaning that the entrance is blocked. I put maze dimensions as 5 for the ease of illustrating it and I used ```self.solution``` which, from what I understood, should have listed coordinates of the cells of the solution path. Also, there are just areas of ```.``` and other areas of ```#```, which doesn’t really look like a maze. I mean it might be solvable in theory (if the entrance and the exit are not blocked or we consider them to be at different coordinates) but I don’t think it should be done that way.  <br/>
<br/>

**Wall follower:** <br/>

<img width="639" alt="terminal_print_wallFollower" src="https://user-images.githubusercontent.com/97029420/185744082-6a3467e7-c0b0-45ad-8f01-01c2682de03c.png">

There are the same issues – ie. the entrance is blocked with ```#```, and there are the ```.``` and ```#``` areas instead of paths between the walls. Also when I print the coordinates from the ```self.solution```, the last tuple always have the coordinates as float numbers whereas the rest of them are integers (see the output of ```print(self.solution)``` in the first line in the terminal). I don’t understand why that happens and what’s the point. </br>
<br/>

Other classes seem to be working :))

**Comment by JanneKarki** [comment]
Hi,

Thank you for your review! I think that the issue you are facing with the missing maze.png is due to some missing library. Do you have poetry installed on your computer and did you run the  "poetry install"-command in the root directory before running the program? maze.png is created when maze is generated. App is quite ready now and should be working. Please let me know if poetry does not fix the issue. Thanks.

**Comment by gitgabbs** [comment]
Hey! Sorry for the late reply, I had a busy week. Poetry is installed and I still get ```FileNotFoundError: [Errno 2] No such file or directory: 'src/data/maze.png'```

**Comment by JanneKarki** [comment]
Ok no problem, thanks for your help. 

I did my solution (column, row) so that explains incorrect solutions that you got  in your tests.

I need to check if I missed some depedencies from poetry because if I take clone from the repository it works fine after depedencies are installed. Just to make sure, did you run the "poetry install"-command in the root and then launched the app with "poetry run invoke start"-command?

**Comment by JanneKarki** [comment]
Btw, your finding about the errors in the solutions were beneficial. In the solution moves are (column, row), even algorithms handle them (row, column). Need to find out where it goes other way around.
